# lists

List processing package.

<a id='notes'></a>

## Notes

**For questions or comments please see [our github page](https://github.com/spacetelescope/stak).  We encourage and appreciate user feedback.**

Contents:

* [Task1](#task1)
* [Task2](#task2)

<br>

<a id='lintran'></a>

## lintran

**Please review the [Notes](#notes) section above before running any examples in this notebook**

The lintran task will linear transfrom a list of coordinates. There are various tasks in the [numpy linear algebra package](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html) that can used to achieve this in Python.  Below is a simple example of a 90 degree rotation.

In [12]:
# Standard Imports
import numpy as np

In [13]:
# 90 degree rotation counterclockwise
x_points = np.array([1,4,5,7,3])
y_points = np.array([4,5,2,2,4])
points = np.vstack([x_points,y_points])
transform_matrix = a = np.array([[0, -1],
                                 [1, 0]])

new_points = np.linalg.inv(a).dot(points)

print("new x values: {}".format(new_points[0]))
print("new xyvalues: {}".format(new_points[1]))

new x values: [ 4.  5.  2.  2.  4.]
new xyvalues: [-1. -4. -5. -7. -3.]


<br>

<a id='raverage'></a>

## raverage

** Please review the [Notes](#notes) section above before running any examples in this notebook **

raverage computes the running average and standard deviation for a 1-dimensional array.  We can efficiently do this in Python using strides in numpy (source: http://www.rigtorp.se/2011/01/01/rolling-statistics-numpy.html).

In [4]:
# Standard Imports
import numpy as np

In [19]:
# code goes here
def rolling_window(a, window):
    shape = a.shape[:-1] + (a.shape[-1] - window + 1, window)
    strides = a.strides + (a.strides[-1],)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)

data = np.arange(20)
out_data = np.mean(rolling_window(data,4),-1)
out_stddev = np.std(rolling_window(data,4),-1)
print(rolling_window(data,5))
print("out_data: {}".format(out_data))
print("out_stddev: {}".format(out_stddev))

[[ 0  1  2  3  4]
 [ 1  2  3  4  5]
 [ 2  3  4  5  6]
 [ 3  4  5  6  7]
 [ 4  5  6  7  8]
 [ 5  6  7  8  9]
 [ 6  7  8  9 10]
 [ 7  8  9 10 11]
 [ 8  9 10 11 12]
 [ 9 10 11 12 13]
 [10 11 12 13 14]
 [11 12 13 14 15]
 [12 13 14 15 16]
 [13 14 15 16 17]
 [14 15 16 17 18]
 [15 16 17 18 19]]
out_data: [  1.5   2.5   3.5   4.5   5.5   6.5   7.5   8.5   9.5  10.5  11.5  12.5
  13.5  14.5  15.5  16.5  17.5]
out_stddev: [ 1.11803399  1.11803399  1.11803399  1.11803399  1.11803399  1.11803399
  1.11803399  1.11803399  1.11803399  1.11803399  1.11803399  1.11803399
  1.11803399  1.11803399  1.11803399  1.11803399  1.11803399]


<br>

<a id='table'></a>

## table

** Please review the [Notes](#notes) section above before running any examples in this notebook **

E

table - Format a list of words into a table (cl.lists)

In [4]:
# Standard Imports
import numpy as np

# Astronomy Specific Imports
from astropy.io import fits

In [5]:
# code goes here

<br>

<a id='unique'></a>

## unique

** Please review the [Notes](#notes) section above before running any examples in this notebook **

E

unique - Delete redundant elements from a list

In [4]:
# Standard Imports
import numpy as np

# Astronomy Specific Imports
from astropy.io import fits

In [5]:
# code goes here

<br>

<a id='words'></a>

## words

** Please review the [Notes](#notes) section above before running any examples in this notebook **

E

 words - Break a file up into a stream of words

In [4]:
# Standard Imports
import numpy as np

# Astronomy Specific Imports
from astropy.io import fits

# Plotting Imports/Setup
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
# code goes here

<br>

## Not Replacing

* average - see **images.imutil.imstatistics** or ``numpy`` tools (https://docs.scipy.org/doc/numpy/reference/routines.statistics.html)
* columns - used to convert multicolumn data into CL lists, deprecated
* rgcursor - Read the graphics cursor, deprecated
* rimcursor - Read the image display cursor, see **images.tv** or [Python imexam](http://imexam.readthedocs.io/en/v0.7.1/)
* tokens - deprecated